# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "httpdocs/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "overall-pages"
    label: "Overall pagina's"
    delete: "false"
    editor:
      preview: false
    files:
      - name: "homepage"
        label: "Homepage"
        file: "/pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false }
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false }
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "het-onderzoek"
        label: "Het onderzoek"
        file: "/pages/het-onderzoek.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "samenvatting"
        label: "Samenvatting"
        file: "/pages/samenvatting.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "uitkomsten"
        label: "Uitkomsten"
        file: "/pages/uitkomsten.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "analyse-en-conclusie"
        label: "Analyse en conclusie"
        file: "/pages/analyse-en-conclusie.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "democratische-meetlat"
        label: "De democratische meetlat"
        file: "/pages/de-democratische-meetlat.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "deelonderzoek-pages"
    label: "Deelonderzoek pagina's"
    delete: "false"
    editor:
      preview: false
    files:
      - name: "g1000"
        label: "G1000"
        file: "/pages/g1000.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "omgevingsvisie"
        label: "Omgevingsvisie"
        file: "/pages/omgevingsvisie.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "mildam"
        label: "Mildam Noord"
        file: "/pages/mildam.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "akkrum"
        label: "Akkrum"
        file: "/pages/akkrum.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "de-greiden"
        label: "De Greiden"
        file: "/pages/de-greiden.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "aldeboarn"
        label: "Aldeboarn"
        file: "/pages/aldeboarn.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string", required: false}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text", required: false}
          - {label: "Intro", name: "content-intro", widget: "text", required: false }
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text", required: false }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "footer"
    label: "Footer"
    delete: "false"
    editor:
      preview: false
    files:
      - name: "footer"
        label: "Footer"
        file: "/_data/footer.yaml"
        fields:
          - {label: "Onderzoekers titel", name: "research-title", widget: "string"}
          - {label: "Onderzoekers paragraaf", name: "research-paragraph", widget: "markdown"}
          - {label: "Vormgeving titel", name: "design-title", widget: "string"}
          - {label: "Vormgeving paragraaf", name: "design-paragraph", widget: "markdown"}
          - {label: "Webontwikkeling titel", name: "web-title", widget: "string"}
          - {label: "Webontwikkeling paragraaf", name: "web-paragraph", widget: "markdown"}
          - {label: "Illustraties titel", name: "illustrations-title", widget: "string"}
          - {label: "Illustraties paragraaf", name: "illustrations-paragraph", widget: "markdown"}
          - {label: "Foto's titel", name: "photos-title", widget: "string"}
          - {label: "Foto's paragraaf", name: "photos-paragraph", widget: "markdown"}
          - {label: "Copyright notice", name: "copyright-notice", widget: "string"}
