# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "_posts" # The path to the folder where the documents are stored
  #   sort: "date:desc" # Default is title:asc
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields: # The fields each document in this collection have
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - label: "Author"
  #       name: "author"
  #       widget: "select"
  #       options:
  #         - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
  #         - { label: "John Doe", value: "john_doe" }
  #     - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}
  #     - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  # - name: "page"
  #   label: "Page"
  #   folder: "pages"
  #   sort: "title:asc"
  #   create: false
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - {label: "Permalink", name: "permalink", widget: "hidden"}
  #     - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}

  # HOMEPAGE
  - name: "overall-pages"
    label: "Overall pagina's"
    delete: "false"
    editor:
      preview: false
    files:
      - name: "homepage"
        label: "Homepage"
        file: "/pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "het-onderzoek"
        label: "Het onderzoek"
        file: "/pages/het-onderzoek.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "samenvatting"
        label: "Samenvatting"
        file: "/pages/samenvatting.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "uitkomsten"
        label: "Uitkomsten"
        file: "/pages/uitkomsten.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "analyse-en-conclusie"
        label: "Analyse en conclusie"
        file: "/pages/analyse-en-conclusie.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "democratische-meetlat"
        label: "De democratische meetlat"
        file: "/pages/de-democratische-meetlat.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "deelonderzoek-pages"
    label: "Deelonderzoek pagina's"
    delete: "false"
    editor:
      preview: false
    files:
      - name: "g1000"
        label: "G1000"
        file: "/pages/g1000.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "omgevingsvisie"
        label: "Omgevingsvisie"
        file: "/pages/omgevingsvisie.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "mildam"
        label: "Mildam Noord"
        file: "/pages/mildam.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "akkrum"
        label: "Akkrum"
        file: "/pages/akkrum.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "de-greiden"
        label: "De Greiden"
        file: "/pages/de-greiden.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "aldeboarn"
        label: "Aldeboarn"
        file: "/pages/aldeboarn.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Browser title tag", name: "title_tag", widget: "string"}
          - {label: "Kleurschema van de pagina (blue of red)", name: "color", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Hoofdtitel", name: "hero-heading", widget: "string"}
          - {label: "Subtitel", name: "hero-subheading", widget: "string"}
          - {label: "Zinnetje bovenaan", name: "hero-paragraph", widget: "text"}
          - label: "Gekleurde navigatieblokjes"
            name: "chapters"
            widget: list
            fields:
              - { label: "Type (research, summary, results of analysis", name: "type", widget: "string" }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Tekst", name: "paragraph", widget: "text" }
              - { label: "Link", name: "url", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown"}
